### PR TITLE
SD card clearing

### PR DESCRIPTION
**Pull request by cameron-goddard**
Clears the SD card on every first-time boot.

A possible concern is that SD.h doesn't like multiple calls to SD.begin(), but it's unclear if it's actually still a problem in the library. It's worth testing and seeing if the call to SD.begin() in CameraControlTask should be taken out.

### CODE REVIEW

**Comment by ljgreenhill** [comment]
> Clears the SD card on every first-time boot.
> 
> A possible concern is that SD.h doesn't like multiple calls to SD.begin(), but it's unclear if it's actually still a problem in the library. It's worth testing and seeing if the call to SD.begin() in CameraControlTask should be taken out.

Is there a way to check if the SD card is already initialized before calling SD.begin() in the CameraControlTask?

**Review by ljgreenhill — CHANGES_REQUESTED** [review]
Unsure if this should be in MissionMode.cpp. Also, how did you test this? Did you try writing an image, clearing it, and then writing a new image?

**Comment by dhacks541** [comment]
#

> > Clears the SD card on every first-time boot.
> > A possible concern is that SD.h doesn't like multiple calls to SD.begin(), but it's unclear if it's actually still a problem in the library. It's worth testing and seeing if the call to SD.begin() in CameraControlTask should be taken out.
> 
> Is there a way to check if the SD card is already initialized before calling SD.begin() in the CameraControlTask?

This is also a question for the fragment downlink command, as the SD card needs to be initialized if the camera hasn't been initialized but there is a fragment on the SD card we want to downlink (as might happen in testing, and maybe in some reboot case?). For now, we got around this by initializing the SD card in the camera report monitor if in the simulator environment. But if there is a way to do this, that would be good to know.

**Comment by cameron-goddard** [comment]
> Unsure if this should be in MissionMode.cpp. Also, how did you test this? Did you try writing an image, clearing it, and then writing a new image?

Yeah, because formatting the SD card isn't really viable anymore (it's a pretty involved process), it might just be worth removing all the file clear stuff and just relying on the tool I just pushed. The tool has a flag where you can choose to create dummy files to test writing/clearing, or just use it to clear any files on the card.

**Review by ljgreenhill — APPROVED** [review]

**Pull request merged**
