### PR TITLE
enabled imu temperature reading

### PR DESCRIPTION
**Pull request by dhacks541**

### CODE REVIEW

**Review by ljgreenhill — COMMENTED** [review]
Was this ever tested on hardware?

**Comment by dhacks541** [comment]
@ljgreenhill Not yet, last time I checked we were waiting for Josh to do some debugging of the actual imu temp sensor before determining whether it's even worth it to do this

**Comment by ljgreenhill** [comment]
@JUmanskyCastro What is the status of this? Converting PR to a draft for now.

**Comment by ljgreenhill** [comment]
@JUmanskyCastro What is the status of this? Converting PR to a draft for now.

**Pull request closed without merging**
